###delivery https

###delivery person post req
POST http://localhost:3000/delivery-api/deliveryPerson
Content-Type: application/json

{
  "profileImg": "https://example1.com/image.jpg",
  "mobileNumber":"+918897410789",
  "firstName":"Harin",
  "lastName":"Pasumarthi",
  "email":"saihari798@gmail.com",
  "dob":"2000-05-15",
  "vechicle":true
}
### update by phone number shopkeeper
PUT http://localhost:3000/delivery-api/deliveryPersonupdate/67ddb5bece05e8d144861985
Content-Type: application/json

{
  "profileImg": "https://example.com/imag.jpg",
  "mobileNumber":"+918897410780",
  "firstName":"Nirup",
  "lastName":"Reddy",
  "email":"saihari798@gmail.com",
  "dob":"2000-05-15",
  "vechicle":true
}

###get all delivery person
GET http://localhost:3000/delivery-api/deliveryPersons

###get delivery person by id
GET http://localhost:3000/delivery-api/deliveryperson/67ddb5bece05e8d144861985

###deleting a delivery person by id
delete http://localhost:3000/delivery-api/deliverypersonid/67ddb5bece05e8d144861985