###user https
### post user
POST http://localhost:3000/user-api/user 
Content-Type: application/json

{
  "profileImg": "https://example.com/image.jpg",
  "mobileNumber": "+919576543219",
  "firstName": "John",
  "lastName": "Doe",
  "email": "johnd@example.com",
  "Address": {
    "state": "Maharashtra",
    "city": "Mumbai",
    "pincode": "400001",
    "address": {
      "flatNO": "101",
      "landmark": "Near Mall",
      "area": "Andheri West"
    }
  }
}

### get user
GET http://localhost:3000/user-api/users

### get user by phone
GET http://localhost:3000/user-api/user/9576543210



###deleting a user
delete http://localhost:3000/user-api/userid/67db0abb68803b2cc4c8b754


###delete a user by specific filed
delete http://localhost:3000/user-api/userph/+919576543219

###shop https

###post request for shop
POST http://localhost:3000/shopkeeper-api/shopkeeper
Content-Type: application/json

{
  "profileImg": "https://example.com/image.jpg",
  "mobileNumber": "+919876543210",
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "shopName": "Doe Electronics",
  "shopAddress": {
    "state": "Maharashtra",
    "city": "Mumbai",
    "pincode": "400001",
    "address": {
      "flatNO": "101",
      "landmark": "Near Mall",
      "area": "Andheri West"
    }
  }
}

###get all shopkeeper
GET http://localhost:3000/shopkeeper-api/shopkeepers

###get shopkeeper by phone
GET http://localhost:3000/shopkeeper-api/shopkeeper/+919876543210

###deleting a shopkeeper
delete http://localhost:3000/shopkeeper-api/shopkeeperid/67db0c166c01de968a84798b


###delete a shopkeeper by specific filed
delete http://localhost:3000/shopkeeper-api/shopkeeperph/+919876543210

