###delivery https

###delivery person post req
POST http://localhost:3000/delivery-api/deliveryPerson
Content-Type: application/json

{
  "profileImg": "https://example1.com/image.jpg",
  "mobileNumber":"+918897410789",
  "firstName":"Harin",
  "lastName":"Pasumarthi",
  "email":"saihari798@gmail.com",
  "dob":"2000-05-15",
  "vechicle":true
}

###get all delivery person
GET http://localhost:3000/delivery-api/deliveryPersons

###get delivery person by phone
GET http://localhost:3000/delivery-api/deliveryperson/+918897410789

###deleting a delivery person by id
delete http://localhost:3000/delivery-api/deliverypersonid/67db0dd74c54132c5cfcc360


###delete a delivery by specific filed
delete http://localhost:3000/delivery-api/deliverypersonph/+918897410789


###worker https
###worker person post req
POST http://localhost:3000/worker-api/worker
Content-Type: application/json

{
  "profileImg":"http://example1.com/image.jpg",
  "mobileNumber":"+918790849561",
  "firstName":"Ravi",
  "lastName":"Karnam",
  "email":"ravi@gmail.com",
  "Address":{
    "state":"Andhra Pradesh",
    "city":"Tiruvuru",
    "pincode":"521235",
    "address":{
      "flatNo":"101",
      "landmark":"Near Main Road",
      "area":"Andheri west"
    }
  }
}

###get all workers
GET http://localhost:3000/worker-api/workers

###get worker by phone
GET http://localhost:3000/worker-api/worker/+918790849561

###update a worker by phone
PUT http://localhost:3000/worker-api/workerupdate/+918790849561
Content-Type: application/json

{
  "profileImg":"http://example1.com/image.jpg",
  "mobileNumber":"+918790849561",
  "firstName":"Praveen",
  "lastName":"Kumar",
  "email":"ravi@gmail.com",
  "Address":{
    "state":"Andhra Pradesh",
    "city":"Tiruvuru",
    "pincode":"521236",
    "address":{
      "flatNo":"101",
      "landmark":"Near Main Road",
      "area":"Andheri west"
    }
  }
}

###deleting a delivery person by id
delete http://localhost:3000/worker-api/workerid/67db11ce395ae69780be1bc1


###delete a delivery by specific filed
delete http://localhost:3000/worker-api/workerph/+918790849561
