    ###get all shopgoods
GET http://localhost:3000/shopgoods-api/shopgoods

###get shopgoods by Id
GET http://localhost:3000/shopgoods-api/shopgood/67dfb54de97ca6599d86b01e

###get shopgoods by name
GET http://localhost:3000/shopgoods-api/shopGood/name/Oil

###get shopgoods by catogery
GET http://localhost:3000/shopgoods-api/shopGood/category/pulses