###shop https

###post request for shop
POST http://localhost:3000/shopkeeper-api/shopkeeper
Content-Type: application/json

{
  "profileImg": "https://example.com/image.jpg",
  "mobileNumber": "+919876543210",
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "shopName": "Doe Electronics",
  "shopAddress": {
    "state": "Maharashtra",
    "city": "Mumbai",
    "pincode": "400001",
    "address": {
      "flatNO": "101",
      "landmark": "Near Mall",
      "area": "Andheri West"
    }
  }
}

###get all shopkeeper
GET http://localhost:3000/shopkeeper-api/shopkeepers

###get shopkeeper by shopKeeperID
GET http://localhost:3000/shopkeeper-api/shopkeeper/943173

###deleting a shopkeeper by db id
delete http://localhost:3000/shopkeeper-api/shopkeeperid/67db0c166c01de968a84798b


###delete a shopkeeper by shopKeeperID
delete http://localhost:3000/shopkeeper-api/shopkeeper/077620

###update a shopKeeper by id
PUT http://localhost:3000/shopKeeper-api/shopKeeperupdate/67e1b2f99d57eabbdf3d0d9e
Content-Type: application/json

{
  "profileImg":"http://example1.com/image.jpg",
  "mobileNumber":"+91879084956",
  "firstName":"Praveen",
  "lastName":"Kumar",
  "email":"ravi@gmail.com",
  "shopAddress":{
    "state":"Andhra Pradesh",
    "city":"Tiruvuru",
    "pincode":"521236",
    "Address":{
      "flatNo":"101",
      "landmark":"Near Main Road",
      "area":"Andheri west"
    }
  }
}

###post new product details 

POST http://localhost:3000/shopkeeper-api/product/67e19f21c8c4370d6bd1c139
Content-Type: application/json

{
   "category": "vegetables",
    "name": ["Onion", "Pyaaz", "Ullipaya", "Periya Vengayam"],
    "imageUrl": "https://res.cloudinary.com/dm22f11c0/image/upload/v1742713064/download_holohs.jpg",
    "description": "Fresh red onions",
    "quantity": 50,
    "price": 30
}

### Delete product details

PUT http://localhost:3000/shopkeeper-api/productChange/67e1908b5f296548ffa521d4/67e192c1a489a003a5cd840b/9/40

    