###user https
### post user
POST http://localhost:3000/user-api/user 
Content-Type: application/json

{
  "profileImg": "https://example.com/image.jpg",
  "mobileNumber": "+919576543219",
  "firstName": "John",
  "lastName": "Doe",
  "email": "johnd@example.com",
  "Address": {
    "state": "Maharashtra",
    "city": "Mumbai",
    "pincode": "400001",
    "address": {
      "flatNO": "101",
      "landmark": "Near Mall",
      "area": "Andheri West"
    }
  }
}

### get user
GET http://localhost:3000/user-api/users

### get user by userid
GET http://localhost:3000/user-api/user/67e1ad3275308107766f7225



###deleting a user
delete http://localhost:3000/user-api/userid/67e1ad3275308107766f7225





###update a user by id
PUT http://localhost:3000/user-api/userupdate/67e1ad3275308107766f7225
Content-Type: application/json

{
  "profileImg":"http://example1.com/image.jpg",
  "mobileNumber":"+918790849561",
  "firstName":"Pravee",
  "lastName":"Kumar",
  "email":"ravi@gmail.com",
  "Address":{
    "state":"Andhra Pradesh",
    "city":"Tiruvuru",
    "pincode":"521236",
    "address":{
      "flatNo":"101",
      "landmark":"Near Main Road",
      "area":"Andheri west"
    }
  }
}

### post comment on worker

POST http://localhost:3000/user-api/userreview/67e1b6b1649045e14f3556cb/67e1b826e63936414426a1ae/
Content-Type: application/json

{
  "rating":5,
  "comment":"This is a great worker"
}
### Delete review on worker
DELETE http://localhost:3000/user-api/userdelete/67e1b6b1649045e14f3556cb/67e1b826e63936414426a1ae/67e1b872e63936414426a1bd